fix: 🐛 fix error
the current code doesn't pass the test due to below error

```
go test -timeout 30s -tags -v -cover -race -count=1 -run ^TestWalk$ github.com/kibitan/go_sample/learn_go_with_test/reflection

--- FAIL: TestWalk (0.00s)
    --- FAIL: TestWalk/struct_with_non_String_field (0.00s)
panic: reflect.Value.Interface: cannot return value obtained from unexported field or method [recovered]
	panic: reflect.Value.Interface: cannot return value obtained from unexported field or method
```

it needs to check the type of the field when the current variable is struct